// Los 66 libros de la Biblia: código USFM (el que usa bible.com), nombre para mostrar, cantidad de capítulos
// y abreviaturas en español (normalizadas: minúsculas, sin acentos ni espacios). Solo datos públicos:
// este proyecto nunca guarda texto bíblico (la TLA tiene derechos de las Sociedades Bíblicas Unidas).
// Joel y Malaquías llevan 4 capítulos para aceptar la numeración de algunas Biblias en español.
export const LIBROS = [
  ["GEN", "Génesis", 50, ["gn", "gen", "gene", "genesis"]],
  ["EXO", "Éxodo", 40, ["ex", "exo", "exod", "exodo"]],
  ["LEV", "Levítico", 27, ["lv", "lev", "levi", "levitico"]],
  ["NUM", "Números", 36, ["nm", "nu", "num", "numeros"]],
  ["DEU", "Deuteronomio", 34, ["dt", "deu", "deut", "deuteronomio"]],
  ["JOS", "Josué", 24, ["jos", "josue"]],
  ["JDG", "Jueces", 21, ["jue", "jc", "jueces"]],
  ["RUT", "Rut", 4, ["rt", "rut"]],
  ["1SA", "1 Samuel", 31, ["1s", "1sa", "1sam", "1samuel"]],
  ["2SA", "2 Samuel", 24, ["2s", "2sa", "2sam", "2samuel"]],
  ["1KI", "1 Reyes", 22, ["1r", "1re", "1rey", "1reyes"]],
  ["2KI", "2 Reyes", 25, ["2r", "2re", "2rey", "2reyes"]],
  ["1CH", "1 Crónicas", 29, ["1cr", "1cro", "1cron", "1cronicas"]],
  ["2CH", "2 Crónicas", 36, ["2cr", "2cro", "2cron", "2cronicas"]],
  ["EZR", "Esdras", 10, ["esd", "esdr", "esdras"]],
  ["NEH", "Nehemías", 13, ["neh", "nehemias"]],
  ["EST", "Ester", 10, ["est", "ester"]],
  ["JOB", "Job", 42, ["job"]],
  ["PSA", "Salmos", 150, ["sal", "salm", "salmo", "salmos", "sl", "slm"]],
  ["PRO", "Proverbios", 31, ["pr", "pro", "prov", "proverbios"]],
  ["ECC", "Eclesiastés", 12, ["ec", "ecl", "ecles", "eclesiastes"]],
  ["SNG", "Cantar de los Cantares", 8, ["cnt", "cant", "cantar", "cantares", "cantardeloscantares"]],
  ["ISA", "Isaías", 66, ["is", "isa", "isaias"]],
  ["JER", "Jeremías", 52, ["jr", "jer", "jeremias"]],
  ["LAM", "Lamentaciones", 5, ["lm", "lam", "lamentaciones"]],
  ["EZK", "Ezequiel", 48, ["ez", "eze", "ezeq", "ezequiel"]],
  ["DAN", "Daniel", 12, ["dn", "dan", "daniel"]],
  ["HOS", "Oseas", 14, ["os", "ose", "oseas"]],
  ["JOL", "Joel", 4, ["jl", "joel"]],
  ["AMO", "Amós", 9, ["am", "amo", "amos"]],
  ["OBA", "Abdías", 1, ["abd", "abdias"]],
  ["JON", "Jonás", 4, ["jon", "jonas"]],
  ["MIC", "Miqueas", 7, ["mi", "miq", "miqueas"]],
  ["NAM", "Nahúm", 3, ["nah", "nahum"]],
  ["HAB", "Habacuc", 3, ["hab", "habacuc"]],
  ["ZEP", "Sofonías", 3, ["sof", "sofonias"]],
  ["HAG", "Hageo", 2, ["hag", "hageo"]],
  ["ZEC", "Zacarías", 14, ["zac", "zacarias"]],
  ["MAL", "Malaquías", 5, ["mal", "malaquias"]],
  ["MAT", "Mateo", 28, ["mt", "mat", "mateo"]],
  ["MRK", "Marcos", 16, ["mr", "mc", "mar", "marcos"]],
  ["LUK", "Lucas", 24, ["lc", "luc", "lucas"]],
  ["JHN", "Juan", 21, ["jn", "jua", "juan"]],
  ["ACT", "Hechos", 28, ["hch", "hech", "hechos"]],
  ["ROM", "Romanos", 16, ["ro", "rom", "romanos"]],
  ["1CO", "1 Corintios", 16, ["1co", "1cor", "1corintios"]],
  ["2CO", "2 Corintios", 13, ["2co", "2cor", "2corintios"]],
  ["GAL", "Gálatas", 6, ["ga", "gal", "galatas"]],
  ["EPH", "Efesios", 6, ["ef", "efe", "efesios"]],
  ["PHP", "Filipenses", 4, ["fil", "flp", "filip", "filipenses"]],
  ["COL", "Colosenses", 4, ["col", "colosenses"]],
  ["1TH", "1 Tesalonicenses", 5, ["1ts", "1tes", "1tesalonicenses"]],
  ["2TH", "2 Tesalonicenses", 3, ["2ts", "2tes", "2tesalonicenses"]],
  ["1TI", "1 Timoteo", 6, ["1ti", "1tim", "1timoteo"]],
  ["2TI", "2 Timoteo", 4, ["2ti", "2tim", "2timoteo"]],
  ["TIT", "Tito", 3, ["tit", "tito"]],
  ["PHM", "Filemón", 1, ["flm", "filem", "filemon"]],
  ["HEB", "Hebreos", 13, ["he", "heb", "hebreos"]],
  ["JAS", "Santiago", 5, ["stg", "sant", "santiago"]],
  ["1PE", "1 Pedro", 5, ["1p", "1pe", "1ped", "1pedro"]],
  ["2PE", "2 Pedro", 3, ["2p", "2pe", "2ped", "2pedro"]],
  ["1JN", "1 Juan", 5, ["1jn", "1jua", "1juan"]],
  ["2JN", "2 Juan", 1, ["2jn", "2jua", "2juan"]],
  ["3JN", "3 Juan", 1, ["3jn", "3jua", "3juan"]],
  ["JUD", "Judas", 1, ["jud", "judas"]],
  ["REV", "Apocalipsis", 22, ["ap", "apo", "apoc", "apocalipsis"]],
];
